### ISSUE TITLE
tcga recurrence data

### ISSUE THREAD

**Issue by Reshiramss** [fmhoward/DLRS#1]
Hi. Thanks for sharing the wonderful work.But I have a question that how to retrieve recurrence scores from the TCGA database?

**Comment by fmhoward** [comment]
Hi - we used estimated recurrence scores computed from gene expression data - our estimate for high / low recurrence score is in: https://github.com/fmhoward/DLRS/blob/main/PROJECTS/UCH_RS/tcga_brca_complete.csv column odx85

**Comment by ml-and-ml** [comment]
How were they estimated? I can't figure this part out after reviewing your code and your paper, in which you write "Statistical formulas from the published development of OncotypeDx29 and MammaPrint30,31 were then applied to the mRNA expression data to calculate research-based recurrence scores." 

I was not able to find any insight into this after reviewing the Oncotype study either

Did you fit expression data to outcome and then generate your own coefficients? I guess this can be done with existing genomic datasets 

Great work by the way.
